# Generated by Django 5.2.17 on 2026-08-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('wood', 'Wood & Orange'), ('slate', 'Cool Slate'), ('terminal', 'Green Terminal')], default='wood', max_length=16),
        ),
    ]
