# Generated by Django 5.2.17 on 2026-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('favicon', models.FileField(blank=True, upload_to='branding/')),
                ('weather_location', models.CharField(blank=True, max_length=120)),
                ('weather_lat', models.FloatField(blank=True, null=True)),
                ('weather_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
