# Generated by Django 5.2.17 on 2026-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='crt_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
