# Generated by Django 5.2.17 on 2026-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_crt_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('latest_version', models.CharField(blank=True, max_length=32)),
                ('release_url', models.URLField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('release_published_at', models.DateTimeField(blank=True, null=True)),
                ('check_error', models.CharField(blank=True, max_length=255)),
                ('install_state', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('install_started_at', models.DateTimeField(blank=True, null=True)),
                ('install_finished_at', models.DateTimeField(blank=True, null=True)),
                ('install_log', models.TextField(blank=True)),
                ('installed_version', models.CharField(blank=True, max_length=32)),
                ('restart_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Update status',
                'verbose_name_plural': 'Update status',
            },
        ),
    ]
