# Generated by Django 5.2.17 on 2026-08-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.URLField()),
                ('icon', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('href', models.URLField()),
                ('icon', models.URLField(blank=True)),
                ('health_check_url', models.URLField(blank=True, help_text='Leave blank to skip checks')),
                ('is_public', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dashboard.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServiceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_up', models.BooleanField()),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='dashboard.service')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
