# Generated by Django 5.2.17 on 2026-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='widget_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='widget_type',
            field=models.CharField(choices=[('none', 'None'), ('pihole', 'Pi-hole'), ('speedtest', 'Speedtest Tracker')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='service',
            name='widget_url',
            field=models.URLField(blank=True, help_text='Widget API base URL'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='layout',
            field=models.CharField(choices=[('grid', 'Grid tiles'), ('rows', 'Full-width rows')], default='grid', max_length=8),
        ),
    ]
