# Generated by Django 5.2.17 on 2026-08-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_service_widget_api_key_service_widget_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='host',
            field=models.CharField(blank=True, help_text='IP or hostname', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, upload_to='service_logos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='path',
            field=models.CharField(blank=True, default='/', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='href',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='layout',
            field=models.CharField(choices=[('grid', 'Grid tiles'), ('rows', 'Wide cards (4-up)')], default='grid', max_length=8),
        ),
        migrations.CreateModel(
            name='ServiceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('json_path', models.CharField(help_text='Dotted path in API JSON, e.g. queries.total', max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.service')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
